apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-k8s-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-k8s-demo
  template:
    metadata:
      labels:
        app: go-k8s-demo
    spec:
      containers:
        - name: go-k8s-demo
          image: go-k8s-demo:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
